version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.9.29-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./config/definitions.json:/etc/rabbitmq/definitions.json:ro
