---
gitea_user_admin_username:
gitea_user_admin_password:
gitea_user_admin_email:

gitea_oauth_google_key:
gitea_oauth_google_secret:

gites_db_username:
gites_db_password:

gitea_config_lfs_jwt_secret:
gitea_config_internal_token:
gitea_config_oauth_provider_jwt_secret:

gites_mailer_password:
gitea_slack_token:

sonarqube_login_username:
sonarqube_login_password_default:
sonarqube_login_password:
vault_sonarqube_postgres_pw:
vault_sonarqube_token:

prod_ssh_port:
prod_ssh_user:
