# Changing default LLM
embabel.models.default-llm=gpt-5
#embabel.models.default-embedding-model=nomic-embed-text:latest

embabel.agent.platform.llm-operations.data-binding.send_validation_info=true
spring.sql.init.mode=always

# Multipart file upload configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
