version: "3.8"
services:
  runner:
    image: ${DOCKER_IMAGE_NAME_GITEA_RUNNER}
    container_name: ${DOCKER_CONTAINER_NAME_RUNNER_MAIN}
    restart: always
    environment:
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: ${GITEA_INSTANCE_URL}
      GITEA_RUNNER_REGISTRATION_TOKEN: ${INSTANCE_REGISTRATION_TOKEN}
      GITEA_RUNNER_NAME: "main-runner"
    volumes:
      - ./main/config.yaml:/config.yaml
      - ./main/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8088:8088"
    networks:
      - gitea-net

networks:
  gitea-net:
    external: true
    name: ${DOCKER_EXTERNAL_NETWORK_NAME}